name: Build Kernel
run-name: Build Kernel for ${{ inputs.firmware }}

on:
  workflow_dispatch:
    inputs:
      firmware:
        description: Stable/Beta?
        required: true
        type: choice
        options:
          - stable
          - beta
      ksu_type:
        description: KernelSU type
        required: true
        type: choice
        options:
          - ksu
          - sukisu
          - ksun

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y p7zip-full zip git curl wget

      - name: First Install
        run: ./first_install.sh

      - name: Build Kernel
        run: ./build_ksu.sh --${{ inputs.firmware }} --${{ inputs.ksu_type }}
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: boot_${{ inputs.firmware }}_${{ inputs.ksu_type }}
          path: output/*
          retention-days: 1
          archive: true
